sudo: required
dist: bionic
language: generic
services:
- docker

branches:
  only:
  - master

# use the Travis CI Matrices feature to build each subdirectory

jobs:
  include:
  - name: "Base for idb-backend"
    env:
      - DOCKERFILE_DIR=base-idb-backend
      - DOCKER_IMAGE_NAME=idigbio/docker-library.base-idb-backend
  - name: "Base for idb-backend (Python3)"
    env:
      - DOCKERFILE_DIR=base-idb-backend-python3
      - DOCKER_IMAGE_NAME=idigbio/docker-library.base-idb-backend-python3
  - name: "idb Tackle Box (Ubuntu 18.04 Bionic)"
    env:
      - DOCKERFILE_DIR=idb-tacklebox-bionic
      - DOCKER_IMAGE_NAME=idigbio/docker-library.idb-tacklebox-bionic

script:
  - docker build -t "$DOCKER_IMAGE_NAME:$TRAVIS_COMMIT" "$DOCKERFILE_DIR"
  - docker tag "$DOCKER_IMAGE_NAME:$TRAVIS_COMMIT" "$DOCKER_IMAGE_NAME:latest"
  - docker images
  - docker login --username="$DOCKER_USERNAME" --password="$DOCKER_PASSWORD"
  - docker push "$DOCKER_IMAGE_NAME:latest"
  - docker push "$DOCKER_IMAGE_NAME:$TRAVIS_COMMIT"

notifications:
  slack:
    secure: "GVJcqmhKww+74MaAKiSPIf2oPxEFp0PoYHzdzL0xw5xd62OiJkrcdzOsiZ5DQxLlgU+MgWrxcxJmunMXOUvR7gt1V1WjuvYsmJ6+bC4/AU81Qr0z5BDANZRX7O8yA/WLvPyE5hsJQWAyBL0NFvkKbxzw/qKlaaoh+uUXI2FLA+LMq6kuW1BYyQuFsoX/14842ppRETrxK5uVAft7c+Egh68Tet5xO5lry3bBFZ0F75Jg5nuzgAgq3OcOe8Luo8FuekX75tBjT0hBNSM+Kn9LOPx25O6tRfivCJn1quOPNSNhet8zbeYecnSevW49VLtWi34fLX6rIsPcvGZg1Z5q1MjvxqDtuIEnhLBeR/8+hK+dLu6MP0YGcG4jBELEH13WlkmJJcH1X+DmRLK1tkgwWhJlW1RJ/QHPoqsMKMNFxS4aDenFGiYXSvv7skX8pr+i2QW1j55V6AU55OCvhsrgyHwFXlA+1ItU5geCVvmLscg8RXF7HuTrZrN/UxLjDVPAjY4rHS2ccZx1g3vo+K0OWafKk6yOi9J7rfwT+OGCMGv3Q57i1ShDIHvmfzfJmsjhtRCvKowwUrw2/Udean/ncdcRLvTTv0Xn+ioxnWAyvWo7UMdXj7YeHvp4bT9pY2eSjfHjB6Fe7S3vWC5zzLc0BDYouxkysv+j0EvP1vx84t4="
